<style>
    .fixed-bottom-wrapper {
        position: fixed;
        bottom: 0;
    }

    .textarea {
        display: block;
        height: 100%;
        width: 600px;
        overflow: hidden;
        resize: none;
        font-size: 1.1rem;
    }

    .textarea[contenteditable]:empty::before {
        content: "Write something...";
        color: gray;
    }

    .textarea:focus {
        outline: none;
        box-shadow: none;
    }

    .chatbubble {
        border-radius: 20px;
    }

    .convobody {
        white-space: nowrap;
        overflow: hidden;
        text-overflow: ellipsis;
    }

    .btn-outline-dark:disabled {
        color: #5a5c68;
        border-color: #5a5c68;
        opacity: 1;
    }
</style>

<script src="https://cdn.jsdelivr.net/npm/chart.js"></script>

<!-- Set base url to javascript variable-->
<script type="text/javascript">
    var base_url = "<?php echo base_url(); ?>";
    var new_chat = "<?= $new_chat ?>";
    var current_con_id = <?= $latest_con_id ?>;
</script>

<body id="page-top">

    <!-- Page Wrapper -->
    <div id="wrapper">

        <!-- Content Wrapper -->
        <div id="content-wrapper" class="d-flex flex-column">

            <!-- Main Content -->
            <div id="content">

                <!-- Begin Page Content -->
                <div class="container-fluid">

                    <!-- Title -->
                    <div class="row">
                        <div class="col-xl-9">
                            <!-- Page Heading -->
                            <div class="d-sm-flex align-items-center justify-content-between mb-4">
                                <h1 class="h3 font-weight-bold" style="color: black">Sales Chatbot</h1>
                            </div>
                        </div>
                        <div class="col-xl-3">
                            <div class="d-flex justify-content-end mb-4">
                                <a type="button" class="btn bluebtn" data-toggle="modal" data-target="#view_item">User Guide<i class="fas fa-info pl-2"></i></a>
                            </div>
                        </div>
                    </div>


                    <!-- Content Row (Start here)-->
                    <div class="row">
                        <div class="col-xl-12">

                            <div class="card shadow ">
                                <div class="card-body" style="min-height: 75vh">

                                    <div class="row ">
                                        <div class="col-xl-2" style="border-right: black;" id="conversation_list" style="max-height: 75vh; overflow-y: auto;">


                                        </div>

                                        <div class="col-xl-10 px-5" id="conversation_body" style="max-height: 78vh; overflow-y: auto; padding-bottom: 200px;">

                                            <div class="row justify-content-center py-2 pt-5" id="new_chat_info" style="padding-left: 20%; padding-right:20%">
                                                <div class="col-md-4 text-center">
                                                    <i class="fas fa-lightbulb pr-2" style="color:#ffcd0a; font-size: 2.0rem;"></i>
                                                    <div class="pb-2" style="font-weight:bold; font-size: 1.2rem;">Examples</div>
                                                    <button type="button" onclick="enter_prompt('Can you give me the top 10 best-selling categories from January 2023 to February 2023?')" class="btn btn-outline-dark mb-2">Can you give me the top 10 best-selling categories from January 2023 to February 2023?</button><br>
                                                    <button type="button" onclick="enter_prompt('Can you give me the top 5 best-earning items from January 2023 to February 2023 in graph format?')" class="btn btn-outline-dark mb-2">Can you give me the top 5 best-earning items from January 2023 to February 2023 in graph format?</button><br>
                                                    <button type="button" onclick="enter_prompt('Compare the sales generated by Adezio and Diabetmin from November 2022 to July 2023')" class="btn btn-outline-dark">Compare the sales generated by Adezio and Diabetmin from November 2022 to July 2023</button>
                                                </div>
                                                <div class="col-md-4 text-center">
                                                    <i class="fas fa-bolt pr-2" style="color:#007AFF; font-size: 2.0rem;"></i>
                                                    <div class="pb-2" style="font-weight:bold; font-size: 1.2rem;">Capabilities</div>
                                                    <button disabled type="button" class="btn btn-outline-dark mb-2">Remembers what user said earlier in the conversation</button><br>
                                                    <button disabled type="button" class="btn btn-outline-dark mb-2">Allows user to provide follow-up corrections</button><br>
                                                    <button disabled type="button" class="btn btn-outline-dark">Trained to decline inappropriate requests</button>
                                                </div>
                                                <div class="col-md-4 text-center">
                                                    <i class="fas fa-exclamation pr-2" style="color:#FF0000; font-size: 2.0rem;"></i>
                                                    <div class="pb-2" style="font-weight:bold; font-size: 1.2rem;">Limitation</div>
                                                    <button disabled type="button" class="btn btn-outline-dark mb-2">May occasionally generate incorrect information</button><br>
                                                    <button disabled type="button" class="btn btn-outline-dark mb-2">May occasionally produce harmful instructions or biased content</button><br>
                                                    <button disabled type="button" class="btn btn-outline-dark">Limited knowledge of world and events after 2021</button>
                                                </div>
                                            </div>


                                        </div>

                                    </div>

                                </div>
                            </div>

                        </div>
                    </div>

                    <!-- Input prompt -->
                    <div class="row">
                        <div class="col-xl-12 d-flex justify-content-center">
                            <div class="fixed-bottom-wrapper mb-5">

                                <div class="card shadow" style="border-radius: 15px;">
                                    <div class="card-body d-flex align-items-center" style="padding-top:10px; padding-bottom:10px;">
                                        <span id="user_prompt" class="textarea" role="textbox" contenteditable></span>
                                        <a onclick="enter_prompt()" class="btn btn-success ml-4 mt-auto" style="margin-right: -7px;"><i class="fas fa-paper-plane"></i></a>
                                    </div>
                                </div>

                            </div>
                        </div>
                    </div>

                </div>
                <!-- /.container-fluid -->

                <!-- User Guide Modal -->
                <div class="modal fade" id="view_item" tabindex="-1" role="dialog" aria-labelledby="view_itemLabel" aria-hidden="true">
                    <div class="modal-dialog modal-xl" role="document">
                        <div class="modal-content">
                            <div class="modal-header" style="background-color:#292e32ff;">
                                <h5 class="modal-title" id="view_itemLabel" style="color:white;">User Guide</h5>
                                <button style="color:white;" type="button" class="close" data-dismiss="modal" aria-label="Close">
                                    <span aria-hidden="true">&times;</span>
                                </button>
                            </div>
                            <div class="modal-body">
                                <div id="accordion">
                                    <!-- Question 1 -->
                                    <div class="card">
                                        <div class="card-header" id="headingOne" data-toggle="collapse" data-target="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
                                            <h6 class="pb-4"><strong>1. Top Selling Categories</strong></h6>
                                            <strong>How to Structure Question:</strong>
                                            <ul>
                                                <li>Can you give me the top <span style="color: #3b75f2; font-weight:800">(number)</span> best-selling category from <span style="color: #1cc88a; font-weight:800;">(date)</span> to <span style="color: #1cc88a; font-weight:800;">(date)</span>?</li>
                                                <li>Can you give me the top <span style="color: #3b75f2; font-weight:800">(number)</span> best-selling category for <span style="color: #1cc88a; font-weight:800;">(month & year)</span>?</li>
                                            </ul>
                                            <p><strong>Sample Question:</strong></p>
                                            <button class="btn btn-outline-secondary mb-2" onclick="enter_prompt('Can you give me the top 10 best-selling categories from January 1 2023 to February 28 2023?')">Can you give me the top 10 best-selling categories from January 1 2023 to February 28 2023?</button>
                                            <button class="btn btn-outline-secondary" onclick="enter_prompt('Can you give me the top 10 best-selling categories from January 2023 to February 2023?')">Can you give me the top 10 best-selling categories from January 2023 to February 2023?</button>
                                        </div>
                                        <div id="collapseOne" class="collapse" aria-labelledby="headingOne" data-parent="#accordion">
                                            <div class="card-body">
                                                <div style="width: 100%;">
                                                    <canvas id="line_chart_sample"></canvas>
                                                </div>
                                            </div>
                                        </div>
                                    </div>

                                    <!-- Question 2 -->
                                    <div class="card">
                                        <div class="card-header" id="headingTwo" data-toggle="collapse" data-target="#collapseTwo" aria-expanded="false" aria-controls="collapseTwo">
                                            <h6 class="pb-4"><strong>2. Top Earning Items in Terms of Sales and Graph Format</strong></h6>
                                            <strong>How to Structure Question:</strong>
                                            <ul>
                                                <li>Can you give me the top <span style="color: #3b75f2; font-weight:800">(number)</span> best-earning items from <span style="color: #1cc88a; font-weight:800;">(date)</span> to <span style="color: #1cc88a; font-weight:800;">(date)</span> in graph format?</li>
                                                <li>Can you give me the top <span style="color: #3b75f2; font-weight:800">(number)</span> best-earning items for <span style="color: #1cc88a; font-weight:800;">(month & year)</span> in graph format?</li>
                                            </ul>
                                            <p><strong>Sample Question:</strong></p>
                                            <button class="btn btn-outline-secondary mb-2" onclick="enter_prompt('Can you give me the top 5 best-earning items from January 1 2023 to February 28 2023 in graph format?')">Can you give me the top 5 best-earning items from January 1 2023 to February 28 2023 in graph format?</button>
                                            <button class="btn btn-outline-secondary" onclick="enter_prompt('Can you give me the top 5 best-earning items from January 2023 to February 2023 in graph format?')">Can you give me the top 5 best-earning items from January 2023 to February 2023 in graph format?</button>
                                        </div>
                                        <div id="collapseTwo" class="collapse" aria-labelledby="headingTwo" data-parent="#accordion">
                                            <div class="card-body">
                                                <canvas id="bar_chart_sample"></canvas>
                                            </div>
                                        </div>
                                    </div>

                                    <!-- Question 3 -->
                                    <div class="card">
                                        <div class="card-header" id="headingThree" data-toggle="collapse" data-target="#collapseThree" aria-expanded="false" aria-controls="collapseThree">
                                            <h6 class="pb-4"><strong>3. Top Earning Items in Table Format</strong></h6>
                                            <strong>How to Structure Question:</strong>
                                            <ul>
                                                <li>Can you give me the top <span style="color: #3b75f2; font-weight:800">(number)</span> best-earning items from <span style="color: #1cc88a; font-weight:800;">(date)</span> to <span style="color: #1cc88a; font-weight:800;">(date)</span> in table format?</li>
                                                <li>Can you give me the top <span style="color: #3b75f2; font-weight:800">(number)</span> best-selling category for <span style="color: #1cc88a; font-weight:800;">July 2023</span> in table format?</li>
                                            </ul>
                                            <p><strong>Sample Question:</strong></p>
                                            <button class="btn btn-outline-secondary mb-2" onclick="enter_prompt('Can you give me the top 5 best-earning items from January 1 2023 to February 28 2023 in table format?')">Can you give me the top 5 best-earning items from January 1 2023 to February 28 2023 in table format?</button>
                                            <button class="btn btn-outline-secondary" onclick="enter_prompt('Can you give me the top 5 best-earning items January 2023 to February 2023 in table format?')">Can you give me the top 5 best-earning items from January 2023 to February 2023 in table format?</button>
                                        </div>
                                        <div id="collapseThree" class="collapse" aria-labelledby="headingThree" data-parent="#accordion">
                                            <div class="card-body">

                                                <table class="table data-table">
                                                    <thead>
                                                        <tr>
                                                            <th colspan="5" style="font-size:1.5rem;" class="text-center">Top 10 best earning item in terms of sales for this month</th>
                                                        </tr>
                                                    </thead>
                                                    <thead>
                                                        <tr>
                                                            <th scope="col">No.</th>
                                                            <th scope="col">Item Name</th>
                                                            <th scope="col">Subcategory</th>
                                                            <th scope="col">Unit Sold</th>
                                                            <th scope="col">Total Sales (RM)</th>
                                                        </tr>
                                                    </thead>
                                                    <tbody>
                                                        <?php
                                                        $counter = 0; // Initialize a counter variable

                                                        foreach ($sales_report_data as $row) {
                                                            if ($counter >= 10) {
                                                                break; // Exit the loop after 10 iterations
                                                            }
                                                        ?>
                                                            <tr>
                                                                <td><?= $counter+1 ?></td>
                                                                <td><?= $row->item_name ?></td>
                                                                <td><?= $row->item_subcategory_name ?></td>
                                                                <td><?= $row->item_total_quantity ?></td>
                                                                <td><?= $row->item_total_sale ?></td>
                                                            </tr>
                                                        <?php
                                                            $counter++; // Increment the counter variable
                                                        }
                                                        ?>

                                                    </tbody>
                                                </table>

                                            </div>
                                        </div>
                                    </div>

                                    <!-- Question 4 -->
                                    <div class="card">
                                        <div class="card-header" id="headingFour" data-toggle="collapse" data-target="#collapseFour" aria-expanded="false" aria-controls="collapseFour">
                                            <h6 class="pb-4"><strong>4. Compare Sales Generated or Unit Sold by Items</strong></h6>
                                            <strong>How to Structure Question:</strong>
                                            <ul>
                                                <li>Compare the <span style="color: #dc3545; font-weight:800">(sales generated or unit sold)</span> by <span style="color: #3b75f2; font-weight:800">(list of items)</span> from <span style="color: #1cc88a; font-weight:800;">(month & year)</span> to <span style="color: #1cc88a; font-weight:800;">(month & year)</span>?</li>
                                            </ul>
                                            <p><strong>Sample Question:</strong></p>
                                            <button class="btn btn-outline-secondary mb-2" onclick="enter_prompt('Compare the sales generated by Adezio, Agrilife and Diabetmin from January 2023 to July 2023')">Compare the sales generated by Adezio, Agrilife and Diabetmin from January 2023 to July 2023</button>
                                            <button class="btn btn-outline-secondary" onclick="enter_prompt('Compare the sales generated by Adezio and Diabetmin from November 2022 to July 2023')">Compare the sales generated by Adezio and Diabetmin from November 2022 to July 2023</button>
                                        </div>
                                        <div id="collapseFour" class="collapse" aria-labelledby="headingFour" data-parent="#accordion">
                                            <div class="card-body">
                                                <canvas id="multi_line_chart_sample"></canvas>
                                            </div>
                                        </div>
                                    </div>
                                </div>


                            </div>
                            <div class="modal-footer">
                                <button type="button" class="btn redbtn" data-dismiss="modal">Close</button>
                            </div>
                        </div>
                    </div>
                </div>
                <!-- /.Modal -->

            </div>
            <!-- End of Main Content -->
            <script>

            </script>